#!/usr/bin/env python3
"""
The business-file corpus (wave 5e): 200 ORDINARY business tables in plain layout (a date, a branch or a region, sometimes a product, one
measure; no metadata column, no flag, no publisher; small counts of 0 to 3, units, amounts with cents; weekly, daily and monthly dates;
sorted or shuffled; with a total row named Total, All, All regions or Grand total in the branch column, the product column or both, or
without one), generated by tools/fixtures/structure/make_business.py. What the engine must do with every one of them:

  * never refuse it and never crash;
  * a file WITH total rows is never read by adding its rows (the total counted with the rows it totals): the engine reads the total's own
    series, and its figures equal the plain sum of the detail rows, over the windows it states (monthly: the latest 12 months and the 12
    before; weekly: 52 weeks; daily: 365 days);
  * a file WITHOUT one is read as it always was: the figure the old engine (main, f334008) printed for it, unchanged
    (tools/fixtures/structure/business_corpus_main.json).

    python tools/test_nl_business.py                 # the corpus (about 3 minutes, one engine process)
    NL_BUSINESS_ONLY=40:60 python tools/test_nl_business.py

Self-running: prints one line per problem and a summary; exits 1 on any.
"""
from __future__ import annotations

import json
import os
import sys
import time

os.environ.setdefault("NL_BROWSER_STRICT", "1")
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(HERE, "fixtures", "structure"))
import check_business_corpus as CB  # noqa: E402
import make_business as MB  # noqa: E402

REF = os.path.join(HERE, "fixtures", "structure", "business_corpus_main.json")


def truth(i: int, rec: dict):
    """(prior, latest, pct) of the plain detail rows over the windows the engine states, or None when it states none."""
    cmp_ = rec.get("comparison") or {}
    if not cmp_.get("latest") or not cmp_.get("prior"):
        return None
    sp = MB.spec_of(i)
    _f, _d, spec = MB.make(i)
    by_date = spec["truth"]["detail_by_date"]
    keyed = {}
    monthly = len(cmp_["latest"][0]) == 7
    for d, v in by_date.items():
        keyed.setdefault(d[:7] if monthly else d, []).append(v)
    keyed = {k: sum(v) for k, v in keyed.items()}

    def window(a: str, b: str):
        return [v for k, v in sorted(keyed.items()) if a <= k <= b]
    lat, pri = window(*cmp_["latest"]), window(*cmp_["prior"])
    if not lat or not pri:
        return None
    flow = str(rec.get("aggregation") or "").startswith("sum")
    f = (lambda xs: sum(xs)) if flow else (lambda xs: sum(xs) / len(xs))
    p, l = f(pri), f(lat)
    return p, l, (100.0 * (l / p - 1.0) if p else None)


def close(a, b, rel=1e-6):
    return a is not None and b is not None and abs(a - b) <= rel * max(1.0, abs(b))


def judge(i: int, rec: dict, ref: dict) -> str:
    """"" when the engine did right by file i, else what it did wrong."""
    sp = MB.spec_of(i)
    if rec.get("crash") or not rec.get("ok"):
        return "crash or not ok: %s" % rec.get("error")
    if rec.get("refused"):
        return "refused: %s" % rec.get("headline")[:160]
    if rec.get("estimand"):
        t = truth(i, rec)
        if t is None:
            return "an estimand whose windows hold no detail row"
        if not (close(rec.get("prior"), t[0]) and close(rec.get("latest"), t[1])):
            return "the figures are not the plain sum of the detail rows: engine %r, plain %r over %s" % (
                (rec.get("prior"), rec.get("latest")), t[:2], rec.get("comparison"))
        return ""
    if sp["total"] is not None:
        return "a file with total rows (%s, %s) was read with its rows added: no estimand, figure %r" % (sp["total"], sp["total_name"], rec.get("pct"))
    old = ref.get(str(i))
    if old is None or old.get("pct") is None:
        return "" if rec.get("pct") is None or True else ""
    if rec.get("pct") is None or not close(rec["pct"], old["pct"], 1e-9):
        return "a file the old engine read gives another figure now: old %r, now %r" % (old["pct"], rec.get("pct"))
    return ""


def main() -> int:
    only = os.environ.get("NL_BUSINESS_ONLY")
    lo, hi = (0, 200)
    if only:
        lo, hi = [int(x) for x in only.split(":")]
    ref = json.load(open(REF)) if os.path.exists(REF) else {}
    t0 = time.perf_counter()
    res = CB.run_corpus(lo, hi - lo, detail=False)
    bad = []
    counts = {"ok": 0}
    for rec in res:
        why = judge(rec["i"], rec, ref)
        if why:
            bad.append((rec["i"], why))
        else:
            counts["ok"] += 1
    for i, why in bad:
        sp = MB.spec_of(i)
        print("  FAIL  file %d (%s, %s, total=%s %s): %s" % (i, sp["freq"], sp["kind"], sp["total"], sp["total_name"], why[:400]))
    est = sum(1 for r in res if r.get("estimand"))
    print("\n%d/%d files right (%d read by their structure, %d by the engine's own analysis); %.0f s" % (
        counts["ok"], len(res), est, len(res) - est, time.perf_counter() - t0))
    print("ALL FILES RIGHT" if not bad else "SOME FILES WRONG")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
